#!/bin/bash
#
# Trivial script to go back to the prior config.txt after a change. By
# the time you call this script, the rpi3-config-mv service will
# already have rotated /boot/config.txt to /boot/config.txt.tbc,
# and /boot/config.txt.lng to /boot.config.txt.
# This script just moves /boot/config.txt.tbc -> /boot/config.txt.rej,
# and then reboots immediately, thereby effectively reverting
# to the prior ('last-known-good') configuration.
#
# Copyright (c) 2018 sakaki <sakaki@deciban.com>
# License: GPL v3+
# NO WARRANTY

if (( $(id -u) != 0)); then
	echo "You need to be root to run this script! Quitting." >&2
	exit 1
fi

readonly CONFIG_PATHNAME="/boot/config.txt"
readonly CONFIG_LNG_PATHNAME="/boot/config.txt.lng"
readonly CONFIG_TBC_PATHNAME="/boot/config.txt.tbc"
readonly CONFIG_REJ_PATHNAME="/boot/config.txt.rej"
readonly CONFIG_OLD_PATHNAME="/boot/config.txt.old"

declare -i need_reboot=0

if [ -f "${CONFIG_TBC_PATHNAME}" ]; then
    # leave tbc file around if requested
    # this allows the rpi3-config-mv service to sweep it
    if [[ "${1}" != "-n" ]]; then
        mv -fv "${CONFIG_TBC_PATHNAME}" "${CONFIG_REJ_PATHNAME}"
    fi
    need_reboot=1
fi
if [ -f "${CONFIG_LNG_PATHNAME}" ]; then
    if [[ "${1}" != "-n" ]]; then
        # user has called this after an edit
        mv -fv "${CONFIG_LNG_PATHNAME}" "${CONFIG_PATHNAME}"
    fi
fi
if ((need_reboot==1)); then
    echo "Changes reverted, rebooting now!"
    reboot
else
    echo "No ${CONFIG_TBC_PATHNAME} file found, not rebooting."
fi
exit $?
