#!/bin/bash
#
# Simple arandr saved settings autoload script.
#
# When invoked on login, will check to see if there is exactly one
# executable ~/.screenlayout/*.sh file, OR if there exists
# an executable ~/.screenlayout/default.sh file, and if so
# runs it after a short delay (to set the saved screen layout).
#
# Copyright (c) 2019 sakaki <sakaki@deciban.com>
# License: GPL v2 or GPL v3+
# NO WARRANTY

DELAY_SECS=0
CONF_DIR="${HOME}/.screenlayout"
DEFAULT_SCRIPT="${CONF_DIR}/default.sh"

if [[ "${XDG_CURRENT_DESKTOP}" != "XFCE" || ! -d "${CONF_DIR}" ]]; then
	exit 0
fi

# check if Ctrl key (scancode 37) is depressed on any
# X input device from 1 to 20
# (assume this will be enough to catch most attached keyboards)
# return 0 if Ctrl depressed, 1 if not
ctrl_is_pressed() {
	local pressed=1
	local D
	for ((D=1;D<=20;D++)); do
		if xinput --query-state ${D} |& grep -q "key\[37\]=down"; then
			pressed=0
			break
		fi
	done
	return ${pressed}
}

# we always run the ~/.screenlayout/default.sh script, if found
# unless the Ctrl key (scan code 37) is pressed; this allows a
# way out if a bad default has been accidentally set
if ctrl_is_pressed; then
	exit 0
fi
if [[ -x "${DEFAULT_SCRIPT}" ]]; then
    sleep ${DELAY_SECS}
    exec "${DEFAULT_SCRIPT}"
else
    NUM_SCRIPTS="$(find "${CONF_DIR}" -mindepth 1 -maxdepth 1 -executable -type f -name '*.sh' | wc -l)"
    if ((NUM_SCRIPTS==1)); then
	SCRIPT_NAME="$(find "${CONF_DIR}" -mindepth 1 -maxdepth 1 -executable -type f -name '*.sh')"
	sleep ${DELAY_SECS}
	exec "${SCRIPT_NAME}"
    fi
fi
exit 0
