#!/bin/bash
#
# Check if the current user has keyboard layouts set up, and if so,
# apply them; used to get around bug where Xfce does not set up the correct
# initial keyboard on login.
#
# Copyright (c) 2020 sakaki <sakaki@deciban.com>
# License: GPL v2 or GPL v3+
# NO WARRANTY

if [[ "${XDG_CURRENT_DESKTOP}" != "XFCE" ]]; then
	exit 0
fi

if [[ "$(xfconf-query --channel keyboard-layout --property /Default/XkbDisable 2>/dev/null)" == "false" ]]; then
    LAYOUT="$(xfconf-query --channel keyboard-layout --property /Default/XkbLayout 2>/dev/null)"
    VARIANT="$(xfconf-query --channel keyboard-layout --property /Default/XkbVariant 2>/dev/null)"
    GROUP="$(xfconf-query --channel keyboard-layout --property /Default/XkbOptions/Group 2>/dev/null)"
    COMPOSE="$(xfconf-query --channel keyboard-layout --property /Default/XkbOptions/Compose 2>/dev/null)"
    OPTS=""
    if [[ "${GROUP}" ]]; then
        OPTS+="-option '${GROUP}' "
    fi
    if [[ "${COMPOSE}" ]]; then
        OPTS+=" -option '${COMPOSE}' "
    fi
    if [[ "${VARIANT//,/}" ]]; then
        VARIANT="-variant '${VARIANT}'"
    else
        VARIANT=""
    fi
    echo $LAYOUT $VARIANT $OPTS
    setxkbmap -layout "${LAYOUT}" ${VARIANT} ${OPTS}
    # force settings to toggle
    xfconf-query --channel keyboard-layout --property /Default/XkbLayout \
        --reset
    xfconf-query --channel keyboard-layout --property /Default/XkbLayout \
        --create --type string --set "${LAYOUT}"
fi
