#!/bin/bash
#
# Install a default volumeicon config for user if none already present (in
# ~/.config/volumeicon/volumeicon); then start volumeicon. User notified on
# first run.
#
# Copyright (c) 2017 sakaki <sakaki@deciban.com>
# License: GPL v3+
# NO WARRANTY

VI="volumeicon"
VI_APP="/usr/bin/${VI}"
VI_CONFIG_DIR="${HOME}/.config/${VI}"
VI_CONFIG_PATH="${VI_CONFIG_DIR}/${VI}"
VI_DEFAULT_CONFIG_PATH="/usr/share/xfce4-mixer/${VI}"

declare -i FIRST_USE=0

if [[ "${XDG_CURRENT_DESKTOP}" != "XFCE" ]]; then
	exit 0
fi

sleep 4

if pidof -o %PPID -x "${VI}" &>/dev/null; then
        # volumeicon already running
        exit 0
fi

if [[ ! -f "${VI_CONFIG_PATH}" ]]; then
	# first start for this user; copy default config
	mkdir -p "VI_CONFIG_DIR"
	cp "VI_DEFAULT_CONFIG_PATH" "VI_CONFIG_PATH"
	FIRST_USE=1
fi

# start volume icon in the background
nohup ${VI_APP} &>/dev/null&

# inform user
if ((FIRST_USE==1)); then
	notify-send --expire-time=$((60*SECS)) \
	"Xfce4 Mixer Replaced" "The Xfce4 Mixer (and panel volume-control plugin) has been removed from the Gentoo tree (bug 628424). For your convenience, this has been replaced on your panel by the volumeicon utility, which offers similar functionality (including keyboard shortcuts)."
fi
